export const jpgFiles = ['./.jpg/wallpaper/Aiguille du Midi.jpg',
'./.jpg/wallpaper/Akiyoshidai.jpg',
'./.jpg/wallpaper/Amsterdam.jpg',
'./.jpg/wallpaper/Andros.jpg',
'./.jpg/wallpaper/Baia del Silenzio.jpg',
'./.jpg/wallpaper/BigBend.jpg',
'./.jpg/wallpaper/Bueng Si Fai.jpg',
'./.jpg/wallpaper/California.jpg',
'./.jpg/wallpaper/Canyonlands.jpg',
'./.jpg/wallpaper/CaoBằng.jpg',
'./.jpg/wallpaper/Carinthia.jpg',
'./.jpg/wallpaper/Centre-ValDeLoire.jpg',
'./.jpg/wallpaper/Chateaudlf.jpg',
'./.jpg/wallpaper/Civita di Bagnoregio.jpg',
'./.jpg/wallpaper/Copenhagen.jpg',
'./.jpg/wallpaper/Corfu.jpg',
'./.jpg/wallpaper/crescent.jpg',
'./.jpg/wallpaper/CátBà.jpg',
'./.jpg/wallpaper/Dolbadarn.jpg',
'./.jpg/wallpaper/Dorset.jpg',
'./.jpg/wallpaper/Dorset_1.jpg',
'./.jpg/wallpaper/Dugongs.jpg',
'./.jpg/wallpaper/Dunnottar.jpg',
'./.jpg/wallpaper/Emirgan.jpg',
'./.jpg/wallpaper/Everglades.jpg',
'./.jpg/wallpaper/Grundlsee.jpg',
'./.jpg/wallpaper/Hachijo.jpg',
'./.jpg/wallpaper/Hague.jpg',
'./.jpg/wallpaper/Halnaker.jpg',
'./.jpg/wallpaper/Happisburgh.jpg',
'./.jpg/wallpaper/HCMUS.jpg',
'./.jpg/wallpaper/Heidelberg.jpg',
'./.jpg/wallpaper/Hibara.jpg',
'./.jpg/wallpaper/Hocking.jpg',
'./.jpg/wallpaper/HoàngCungTokyo.jpg',
'./.jpg/wallpaper/HồYamanaka.jpg',
'./.jpg/wallpaper/Iceland.1.jpg',
'./.jpg/wallpaper/Iceland.jpg',
'./.jpg/wallpaper/ISS.jpg',
'./.jpg/wallpaper/Iwakuni.jpg',
'./.jpg/wallpaper/Killarnery.jpg',
'./.jpg/wallpaper/Lingmoor.jpg',
'./.jpg/wallpaper/Lofoten.jpg',
'./.jpg/wallpaper/LâuĐàiHimeji.jpg',
'./.jpg/wallpaper/Marseille.jpg',
'./.jpg/wallpaper/Matsumoto.jpg',
'./.jpg/wallpaper/Namib.jpg',
'./.jpg/wallpaper/namibia.jpg',
'./.jpg/wallpaper/New hampshire.jpg',
'./.jpg/wallpaper/Normandy.jpg',
'./.jpg/wallpaper/Nusa.jpg',
'./.jpg/wallpaper/Ordesay y Monte Perdido.jpg',
'./.jpg/wallpaper/Osaka.jpg',
'./.jpg/wallpaper/Petit Minou.jpg',
'./.jpg/wallpaper/Raja Ampat.jpg',
'./.jpg/wallpaper/Roussanou Monastery.jpg',
'./.jpg/wallpaper/Sechura.jpg',
'./.jpg/wallpaper/Shikotsu-Toya.jpg',
'./.jpg/wallpaper/ShinjukuGyoen.jpg',
'./.jpg/wallpaper/Suffolk.jpg',
'./.jpg/wallpaper/Sweden.jpg',
'./.jpg/wallpaper/SôngCửuLong.jpg',
'./.jpg/wallpaper/Tekapo.jpg',
'./.jpg/wallpaper/Tenerife.jpg',
'./.jpg/wallpaper/the ruhr.jpg',
'./.jpg/wallpaper/Trinidad.jpg',
'./.jpg/wallpaper/UnionSquare.jpg',
'./.jpg/wallpaper/Vallee Blanche.jpg',
'./.jpg/wallpaper/Vigo.jpg',
'./.jpg/wallpaper/VũngNapa.jpg',
'./.jpg/wallpaper/Wollongong.jpg',
'./.jpg/wallpaper/Yellowstone.jpg',
'./.jpg/wallpaper/YorkshireDales.jpg']