export const wavFiles = ['./.wav/startup/CrashMacII.wav',
'./.wav/startup/CrashMacIIfx.wav',
'./.wav/startup/CrashMacLC.wav',
'./.wav/startup/CrashMacQuadra.wav',
'./.wav/startup/StartupIntelPreT2Mac.wav',
'./.wav/startup/StartupMacI.wav',
'./.wav/startup/StartupMacQuadra.wav',
'./.wav/startup/StartupPowerMacPCI.wav',
'./.wav/startup/Windows7.wav',
'./.wav/startup/Windows95.wav',
'./.wav/startup/Windows98.wav',
'./.wav/startup/WindowsME.wav',
'./.wav/startup/WindowsNT4.wav',
'./.wav/startup/WindowsXP.wav']